name: Linux Build

on:
  # see https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#on
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        shell: bash
        run: |
          echo "OS information"
          echo "  > Run on Linux"
          echo "$(cat /etc/lsb-release)"
          echo "  > Generic information: $(uname -a)"
